### PR TITLE
BLOG - Cassandra 4.1 is here + homepage update

### PR DESCRIPTION
**Pull request by ErickRamirezAU**
Patch by Chris Thornett, Diogenese Topper, Erick Ramirez; reviewed by Erick Ramirez, --- for CASSANDRA-18063

### CODE REVIEW

**Comment by ErickRamirezAU** [comment]
🛑 Do NOT commit without updating the publish date in `pages/index.adoc` + `pages/blog/Cassandra-4.1-is-here.adoc`. 🛑

**Comment by michaelsembwever** [comment]
Curious if we should replace "Stable" in the titles, with "Rock Solid". 

(If we have to make a point that we are "_only stable_", it has the wrong emphasis…)

**Comment by ErickRamirezAU** [comment]
> Curious if we should replace "Stable" in the titles, with "Rock Solid".
> 
> (If we have to make a point that we are "_only stable_", it has the wrong emphasis…)

I like it! I've updated both the homepage + blog post title. 👍

**Review by michaelsembwever — APPROVED** [review]

**Comment by michaelsembwever** [comment]
merged with 4f139602d7ed849efe1ff461e061ec5f5acc5ba6

**Pull request closed without merging**
