### PR TITLE
BLOG - Apache Cassandra 5.0 Features: Dynamic Data Masking

### PR DESCRIPTION
**Pull request by nonstopdtop**
patch by Diogenese Topper; reviewed by -- for CASSANDRA-18923

### CODE REVIEW

**Review by michaelsembwever — CHANGES_REQUESTED** [review]
the build failed: https://github.com/nonstopdtop/cassandra-website/actions/runs/6489769009/job/17624559599

**Comment by nonstopdtop** [comment]
Fixed.
Preview here: https://raw.githack.com/nonstopdtop/cassandra-website/CASSANDRA-18923_generated/content/_/blog/Apache-Cassandra-5.0-Features-Dynamic-Data-Masking.html

**Review by michaelsembwever — CHANGES_REQUESTED** [review]
LGTM

Except, i'm not the author !

**Comment by nonstopdtop** [comment]
Oh, I thought that you were! Is this an Apache Cassandra Community blog then? @michaelsembwever

**Comment by michaelsembwever** [comment]
`Andrés de la Peña` 

see original gdoc: https://docs.google.com/document/d/11YA1E6iycknipD1qL4dEgCGoluvByDq1g-h95e5ibgs/edit#heading=h.tu8n14g1lot

**Comment by nonstopdtop** [comment]
Author changed. Merged.

**Pull request closed without merging**
