### PR TITLE
WEBSITE - Add DoorDash blog post to Resources section

### PR DESCRIPTION
**Pull request by tonyxrandall**
patch by Anthony Palomarez; reviewed by Michael Semb Wever, Erick Ramirez for CASSANDRA-18279

Added a resource and fixed a typo

### CODE REVIEW

**Review by michaelsembwever — APPROVED** [review]
LGTM.

@ErickRamirezAU , how do we order things on this page? Is resources or blogs a better page for this?

**Comment by ErickRamirezAU** [comment]
> @ErickRamirezAU , how do we order things on this page? Is resources or blogs a better page for this?

There's no real ordering on the **Resources** section so the last update was just added to the end as well. 🙂

**Review by ErickRamirezAU — APPROVED** [review]
Thanks @tonyxrandall ! 🍻

**Comment by ErickRamirezAU** [comment]
I've logged CASSANDRA-18279 and here is the local render of the page:

c18279-01-resources

**Comment by ErickRamirezAU** [comment]
Sorry, I forgot to commit this last week as I got distracted. It's live on the website now. 🙏

**Pull request merged**
