### PR TITLE
DOC - Update quickstart.adoc docker run instruction to open ports to make subsequent cqlsh command work.

### PR DESCRIPTION
**Pull request by juliangamble**
DOC - Update `quickstart.adoc` docker run instruction to open ports to make subsequent `cqlsh` command work.

Hopefully this is helpful. It wouldn't work without it for me. 

Let me know if you have any feedback.

### CODE REVIEW

**Comment by michaelsembwever** [comment]
@ErickRamirezAU can you verify? (I thought the purpose of `docker network create cassandra` was to avoid/better-solve this…?)

**Comment by juliangamble** [comment]
@ErickRamirezAU - I'm in Sydney at BT. We're on one of the Sydney Datastax Accounts. Next time you're in Sydney drop by for a beer!

**Comment by juliangamble** [comment]
@michaelsembwever - I just realised you're in Australia too! Offer goes to you as well!

**Comment by ErickRamirezAU** [comment]
> @ErickRamirezAU - I'm in Sydney at BT. We're on one of the Sydney Datastax Accounts. Next time you're in Sydney drop by for a beer!

I'll take you up on that offer. Hopefully sometime soon in time for the Christmas party season probably late November. 🍻

**Comment by ErickRamirezAU** [comment]
> DOC - Update `quickstart.adoc` docker run instruction to open ports to make subsequent `cqlsh` command work.
> 
> Hopefully this is helpful. It wouldn't work without it for me.
> 
> Let me know if you have any feedback.

Thanks for submitting a PR and we're always looking for new contributors so this is very welcome indeed.

We've tried to make the Quickstart guide overly simplistic to make it easy for new users to get up and running pretty quickly. We didn't expose the ports by design because the intent is that it should only be accessible locally.

Were you connecting to the container from outside the host? If so then I guess it's necessary to expose the ports but for the purposes of the guide, it isn't required. Cheers! 🍻

**Comment by juliangamble** [comment]
> Were you connecting to the container from outside the host? 

No - same host. Running on my mac in two terminal windows with Docker Desktop.

**Comment by ErickRamirezAU** [comment]
> No - same host. Running on my mac in two terminal windows with Docker Desktop.

Hmm, I'm on a [non-M1] Mac and this is what I've done:
- clean install of Docker Desktop
- clean install of Cassandra with:

```
$ docker pull cassandra:latest
$ docker network create cassandra
$ docker run --rm -d --name cassandra --hostname cassandra --network cassandra cassandra
```

```
$ docker ps -a
CONTAINER ID   IMAGE       COMMAND                  CREATED         STATUS         PORTS                                         NAMES
eaa18253ea09   cassandra   "docker-entrypoint.s…"   4 seconds ago   Up 3 seconds   7000-7001/tcp, 7199/tcp, 9042/tcp, 9160/tcp   cassandra
```

I managed to connect with `cqlsh` without issues:

```
$ docker run --rm -it --network cassandra nuvo/docker-cqlsh cqlsh cassandra 9042 --cqlversion='3.4.5'
Connected to Test Cluster at cassandra:9042.
[cqlsh 5.0.1 | Cassandra 4.0.6 | CQL spec 3.4.5 | Native protocol v5]
Use HELP for help.
cqlsh>
```

I have to admit I'm not a Docker expert so I'm not sure how to troubleshoot the problem you ran into.

**Comment by juliangamble** [comment]
Got it. 
Thanks - originally that failed same as before...

    Connection error: ('Unable to connect to any servers', {'172.18.0.2': error(111, "Tried connecting to [('172.18.0.2', 9042)]. Last error: Connection refused")})

but when I left it for 5 mins (for Cassandra to start up?) it worked. (I'm on an M1 Mac - which should be reasonably performant.) I clearly lack the mechanical sympathy to know when Cassandra is running vs starting up. (I imagine most new users would as well.)

Perhaps I need to amend this pull request to leave out the ports and say "if you get this error, wait 5 mins for Cassandra to start up. "

**Pull request closed without merging**
