### PR TITLE
just do `ant gen-doc` instead

### PR DESCRIPTION
**Pull request by michaelsembwever**
as all cassandra sources that have an antora build and asciidocs also have the gen-nodetool-docs.py and convert_yaml_to_adoc.py

### CODE REVIEW

**Comment by michaelsembwever** [comment]
depends on https://github.com/polandll/cassandra/pull/16

@ossarga

**Comment by michaelsembwever** [comment]
@ossarga , quick question: why isn't `-u cassandra-website:$(pwd)` the default? 
(and when would you want to have cassandra-website something else than the current git working directory you are in?)

**Comment by ossarga** [comment]
> quick question: why isn't -u cassandra-website:$(pwd) the default?

@michaelsembwever it is. The `./run.sh` script takes care of this in the [run_docker_website_command](https://github.com/apache/cassandra-website/blob/trunk/run.sh#L489-L505) function.

**Comment by michaelsembwever** [comment]
> The ./run.sh script takes care of this in the run_docker_website_command function.

Cool. When I was testing this PR I had to supply that option. The first run without it did not pick up my modifications. I can debug and further validate in a separate issue/PR later on.

**Comment by michaelsembwever** [comment]
This is ready to go out. (I forgot about it, it is still part of CASSANDRA-16763)

**Comment by ossarga** [comment]
@michaelsembwever yes, these changes are good to commit. I tested the change in conjunction with the Cassandra changes, just after the latest commit (66cce0a) was pushed to the branch. It all worked fine for me.

**Comment by michaelsembwever** [comment]
manually merged with https://github.com/apache/cassandra-website/commit/217b35b4f26b5d71388926d09b526d53b8fecf01

**Pull request closed without merging**
