### PR TITLE
GSoD proposal for 2023 blog

### PR DESCRIPTION
**Pull request by polandll**
This blog post needs to be up in order for me to apply to the Google Season of Documentation - the proposal is contained in the page. I've built locally, and I'm happy with the results. Hoping someone, perhaps @michaelsembwever can review for merging?

### CODE REVIEW

**Comment by michaelsembwever** [comment]
> I've built locally, and I'm happy with the results.

screenshot next time please. (otherwise i need to go through the build process too. aside, it would be so nice with GHA that push the generated contents to a branch like `GSoD-proposal-2023__generated`)

**Comment by michaelsembwever** [comment]
> You can find more details about the program on the official [https://developers.google.com/season-of-docs/docs/tech-writer-guide](https://https//developers.google.com/season-of-docs/docs/tech-writer-guide) [GSoD^] website.

Sentence did not rendered correctly. This can be fixed separately.


And, do we want the budget explicit on the page? (is this a requirement to the proposal?)

**Review by michaelsembwever — APPROVED** [review]

**Comment by michaelsembwever** [comment]
Will you also want a tile on the blog index page?

**Comment by michaelsembwever** [comment]
staging: https://cassandra.staged.apache.org/_/blog/GSoD-Proposal-2023.html

let me know if/when you want this pushed live.

**Comment by polandll** [comment]
Sorry, didn't realize to make a screenshot. Yes, the proposal needs the budget. Yes, please, a tile on the blog index page would be nice - do you want me to do that under a different PR, along with the sentence fix?

**Comment by michaelsembwever** [comment]
> a tile on the blog index page would be nice - do you want me to do that under a different PR, along with the sentence fix?

yes please. do you want me to push the current page out as it is, or what for this separate PR ?

**Pull request merged**
