### PR TITLE
Add glossary terms

### PR DESCRIPTION
**Pull request by polandll**
I have not created a ticket for this - just adding some terms that are missing.

### CODE REVIEW

**Comment by michaelsembwever** [comment]
The deleted files should not (cannot) be deleted. The first commit needs to be removed.

The generated file in preview looks a bit odd (includes failing)
https://raw.githack.com/polandll/cassandra-website/add-glossary-terms_generated/content/_/glossary.html

**Comment by polandll** [comment]
Yeah, that is weird! I was copying this style: https://docs.datastax.com/en/glossary/docs/ . I'll see if I can get it fixed up, sorry about that.

**Comment by michaelsembwever** [comment]
LGTM.

note, there's a full alphabet listing under each alphabet character sub-heading.  is that intended ? 
(using the same preview links above, it updates after each new commit on the branch)

**Comment by polandll** [comment]
Yes, that is intended as a navigational aid.

**Comment by michaelsembwever** [comment]
Committed as https://github.com/apache/cassandra-website/commit/207dbf1f831d50daa3b0b35caa348d3e9423959a

**Pull request closed without merging**
