### PR TITLE
blog post on Apache Cassandra 4.0-beta1

### PR DESCRIPTION
**Pull request by michaelsembwever**
ref:
  - https://lists.apache.org/thread.html/r4a5c9c471a64b93c8ea6b85d23f7592f8586b57071ac76ba75f07e78%40%3Cdev.cassandra.apache.org%3E
  - https://lists.apache.org/thread.html/r537fe799e7d5e6d72ac791fdbe9098ef0344c55400c7f68ff65abe51%40%3Cdev.cassandra.apache.org%3E
  - https://lists.apache.org/thread.html/r80c4fc2679dc76560feea42c49d771daf0434ce2a66d318f1532861a%40%3Cprivate.cassandra.apache.org%3E

### CODE REVIEW

**Comment by loganloganlogan** [comment]
Is there a link to the Docker image that should be added? In the last paragraph: "To download the Beta, head to the [Apache Cassandra downloads site](https://www.apache.org/dyn/closer.lua/cassandra/4.0-beta1/apache-cassandra-4.0-beta1-bin.tar.gz) or pull the **Docker image**."

**Comment by michaelsembwever** [comment]
> Is there a link to the Docker image that should be added? In the last paragraph: "To download the Beta, head to the Apache Cassandra downloads site or pull the Docker image."

There's no docker image yet for this release. Good catch. I shall remove it.

**Comment by jeffjirsa** [comment]
lgtm.

**Comment by michaelsembwever** [comment]
thank you @jeffjirsa

**Pull request merged**
