### PR TITLE
Blog cassandra usage report 2020

### PR DESCRIPTION
**Pull request by loganloganlogan**
Publish date is suggested as Monday, October 26.

Dev Slack thread: https://lists.apache.org/thread.html/rd9b53fa8d3e8c5b3c22032bcd798b4b4e281fd900d4c9e66dfd6f2c6%40%3Cdev.cassandra.apache.org%3E

### CODE REVIEW

**Comment by michaelsembwever** [comment]
It's looks like only the *latter commits* in this PR is relevant. (EDIT)

**Comment by michaelsembwever** [comment]
@erickramirezDSE were you interested in reviewing this? 🙏

**Comment by ErickRamirezAU** [comment]
Hey, sure thing. I'll get started on it. 👍

**Review by ErickRamirezAU — CHANGES_REQUESTED** [review]
@loganloganlogan There's a few minor nits/housekeeping to fix but perhaps would require a new PR mostly because I think the Usage Report got thrown into the mix. My recommendations are:
1. Update the PR title to "Blog Cassandra Changelog 01".
2. Clear out commits for Usage Report blog so we're only left with f681e81 and c83721f.
3. Fixing the commits should cleanup the files to not include items such as `Gemfile`, `Gemfile.lock` and images for the Usage Report blog.
4. Rename file to include suffix for consistency, i.e. `2020-10-23-cass_changelog_1.markdown`.
5. In the Tutorials section, fix typo `searech` in first paragraph.

I've noted that the header and footer images are in `src/img`. I assume that they'll be shared resources in future blog posts. Cheers!

**Review by ErickRamirezAU — CHANGES_REQUESTED** [review]
Adding too that the URIs for the header and footer need to be updated with a leading slash (`/`). For example:

```
![Cassandra Changelog header](img/changelog_header.jpg "image_tooltip")
```

should be:

```
![Cassandra Changelog header](/img/changelog_header.jpg "image_header")
```

**Comment by ErickRamirezAU** [comment]
P.S. @loganloganlogan let me know if you need a hand with starting with a fresh PR so only commits for the Changelog blog post are included. Cheers! 🍻

**Pull request closed without merging**
