### PR TITLE
Blog Cassandra Changelog #3

### PR DESCRIPTION
**Pull request by loganloganlogan**
Submitting per note on dev Slack.

### CODE REVIEW

**Comment by ErickRamirezAU** [comment]
Melissa, it looks good to me. I've noted that the embedded YouTube widget (for the Kubernetes SIG video) originally included in [the gDoc draft](https://docs.google.com/document/d/16F4LLc5YBctMCMrW2JzJi8YYlZHVh8skUJ6cU9YSIjE/edit?usp=sharing) is missing from this PR. Cheers!

**Comment by loganloganlogan** [comment]
Thanks @flightc! The embed didn't work in markdown so we changed it.

@michaelsembwever over to you for publishing. Holler with questions. Thanks!

**Comment by michaelsembwever** [comment]
I will start on this later today.

**Comment by loganloganlogan** [comment]
Thank you! What's a good process for changing the date to match the publish date just before pushing it live? It currently says Jan. 11. @michaelsembwever

**Comment by michaelsembwever** [comment]
> What's a good process for changing the date to match the publish date just before pushing it live? It currently says Jan. 11. @michaelsembwever

I can bump it. It's either requires coordination between us, or it's up to the person the ends up git merging/pushing it.

**Comment by michaelsembwever** [comment]
Merged with https://github.com/apache/cassandra-website/commit/f14bf421188c8b095d0baa0c8f1e346b4bc61076 

Planned to publish it live on Tuesday.

**Pull request closed without merging**
