### PR TITLE
CASSANDRA-17696 WEBSITE - Updating Ecosystem information for Anant

### PR DESCRIPTION
**Pull request by adp8ke**
@michaelsembwever + @ErickRamirezAU 
Apologies for closing the previous PR. I have remade a clean PR with only the approved changes from the previous.

Here is the JIRA ticket that was for the previous PR as well: [CASSANDRA-17696](https://issues.apache.org/jira/browse/CASSANDRA-17696)

### CODE REVIEW

**Comment by adp8ke** [comment]
@michaelsembwever @ErickRamirezAU following up in case this fell through the cracks

**Review by michaelsembwever — APPROVED** [review]
LGTM. Leave it to you @ErickRamirezAU to merge.

**Comment by adp8ke** [comment]
@ErickRamirezAU, following up on this in case it fell through the cracks

**Comment by michaelsembwever** [comment]
@adp8ke , Erick has been afk the past week. He'll get to it when he can, it's not forgotten!

**Comment by ErickRamirezAU** [comment]
@adp8ke what's your user name on [jira](https://issues.apache.org/jira/browse/CASSANDRA)?

**Review by ErickRamirezAU — APPROVED** [review]
This is ready for me to commit. I just need to know @adp8ke 's JIRA username. 👍

**Comment by adp8ke** [comment]
@ErickRamirezAU acknowledged, my username is arpan.patel

**Pull request merged**
