### PR TITLE
CASSANDRA-17935 September 2022 blog "Cassandra Summit Returns in 2023"

### PR DESCRIPTION
**Pull request by nonstopdtop**
patch by Diogenese Topper; reviewed by --for CASSANDRA-17935

Authored by: Diogenese Topper <diogenese@constantia.io>

### CODE REVIEW

**Comment by michaelsembwever** [comment]
Screenshot 2022-09-30 at 00 00 44

**Comment by michaelsembwever** [comment]
Screenshot 2022-09-30 at 00 03 09
Screenshot 2022-09-30 at 00 03 27

**Review by michaelsembwever — APPROVED** [review]

**Comment by michaelsembwever** [comment]
@cthornett can you check please

**Comment by cthornett** [comment]
Visual check of screenshots done. No breaking issues that I can see or text uses. Suggest we add an image after the post is published.

**Comment by michaelsembwever** [comment]
merged with 9a83b59d55fc30c2611a89b9ac9eca5f6228b1ca

**Pull request closed without merging**
