### PR TITLE
CASSANDRA-17957 - Adding social media llinks and caption style updates

### PR DESCRIPTION
**Pull request by paulSharecare**
This is to address a request to add social media links to the site as well. Social links have been added to the header and footer of the site as well as the community page under the discussions section.

Additionally, a few minor style updates have been added to address image captions.

### CODE REVIEW

**Review by michaelsembwever — CHANGES_REQUESTED** [review]
The https://github.com/apache/cassandra-website/blob/trunk/site-content/source/modules/ROOT/pages/blog/Apache-Cassandra-Changelog-19-September-2022.adoc file already exists.

Can you rebase this work off trunk, so it's clearly to see what is changing and easier to eventually merge…

**Comment by paulSharecare** [comment]
@michaelsembwever  Apologies. I was helping Diogenese get a screenshot of that post and forgot to remove it.  I have rebased and pushed my branch again.

**Comment by michaelsembwever** [comment]
>  I was helping Diogenese get a screenshot of that post 

do we have a screenshot (you want to post here) ?

**Comment by paulSharecare** [comment]
changelog-19

**Comment by paulSharecare** [comment]
@michaelsembwever  I added the screenshot of the post.  The screenshots for the other changes to the site can be viewed here https://issues.apache.org/jira/browse/CASSANDRA-17957

**Comment by michaelsembwever** [comment]
screenshots make a world of difference to the speed of the review. thank you!

**Comment by michaelsembwever** [comment]
merged manually with https://github.com/apache/cassandra-website/commit/e5cbbab627644a84922c8dbbb1ab94e2e27f6712

**Pull request closed without merging**
