### PR TITLE
Fix blackrock broken image on front page

### PR DESCRIPTION
**Pull request by justinmclean**

### CODE REVIEW

**Comment by michaelsembwever** [comment]
@jtlevy do we need this fix? (it is already fixed in the `asf-site` branch)

@justinmclean , the website is in a temporary hacked state at the moment. Josh, Paul, and @ossarga are working on an antora build of the new design that will land in trunk (CASSANDRA-16066). In the meantime the `asf-site` branch is just the html files for the new design. more background info in https://lists.apache.org/thread.html/rab8295c4844a4a5da4028a13b496ac89987939f5197f60d59099429c%40%3Cdev.cassandra.apache.org%3E

**Comment by justinmclean** [comment]
Thanks for the background info. I could be missing something but I can't see the fix in the ash-site branch, either way the live site is currently displaying that broken image, so you might want to fix it.

**Comment by michaelsembwever** [comment]
> I could be missing something but I can't see the fix in the ash-site branch, either way the live site is currently displaying that broken image, so you might want to fix it.

You're quite right. (Last week it was only fixed on the 'case studies' page.)

**Comment by michaelsembwever** [comment]
Thanks @justinmclean 

Manually committed to the `asf-site` branch with d9a4143276fca255e3688bb0ccfc2222ca36428a

**Pull request closed without merging**
